name: CD

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x

      - name: Restore Workloads
        run: dotnet workload restore ./src/Maui.ProgressRing/Maui.ProgressRing.csproj

      - name: Restore Dependencies
        run: dotnet restore ./src/Maui.ProgressRing/Maui.ProgressRing.csproj

      - name: Build Library
        run: dotnet build ./src/Maui.ProgressRing/Maui.ProgressRing.csproj -c Release

      - name: Pack NuGet
        run: dotnet pack ./src/Maui.ProgressRing/Maui.ProgressRing.csproj -c Release -o ./nupkg -p:GeneratePackageOnBuild=false

      - name: Push to NuGet
        run: dotnet nuget push ./nupkg/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate
